# -*- coding: utf-8 -*-
제우스

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1EuOJMt6LQzlo3ElEnq5yFXGI-0irpX





import streamlit as st
import yfinance as yf
import FinanceDataReader as fdr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

# 한글 폰트 설정
plt.rcParams['font.sans-serif'] = ['DejaVu Sans']

# -------------------------------------------------------------------------
# 1. 페이지 설정
# -------------------------------------------------------------------------
st.set_page_config(page_title="글로벌 퀀트 & AI 스캐너", page_icon="🧭", layout="wide")

st.title("🧭 글로벌 포트폴리오 & AI 종목 스캐너")
st.markdown("자산 분석, 세후 수익률, 최적화 엔진에 이어 **한국/미국 주식 시장 주도주 스캔 엔진**이 탑재되었습니다.")

# -------------------------------------------------------------------------
# 2. 포트폴리오 상태 초기화 (Session State 활용)
# -------------------------------------------------------------------------
# 앱이 새로고침 되어도 입력한 포트폴리오가 날아가지 않도록 세션에 저장합니다.
if 'us_portfolio_df' not in st.session_state:
    st.session_state.us_portfolio_df = pd.DataFrame([
        {"티커(Ticker)": "SPY", "수량": 10.0, "매수단가($)": 500.0},
        {"티커(Ticker)": "NVDA", "수량": 20.0, "매수단가($)": 100.0}
    ])

if 'kr_portfolio_df' not in st.session_state:
    st.session_state.kr_portfolio_df = pd.DataFrame([
        {"티커(6자리)": "005930", "수량": 100.0, "매수단가(₩)": 75000.0}
    ])

# -------------------------------------------------------------------------
# 3. 사이드바: 환경 설정 및 동적 자산 입력 (Data Editor)
# -------------------------------------------------------------------------
st.sidebar.header("⚙️ 분석 환경 설정")
risk_free_rate = st.sidebar.number_input("무위험 이자율(예금 금리, %)", value=3.5, step=0.1) / 100

st.sidebar.markdown("---")
st.sidebar.header("💼 내 글로벌 포트폴리오")
st.sidebar.caption("💡 표 맨 아래를 클릭해 자유롭게 종목을 추가하세요. 행을 선택하고 Delete 키를 누르면 삭제됩니다.")

st.sidebar.subheader("🇺🇸 미국 주식 (달러)")
edited_us_df = st.sidebar.data_editor(
    st.session_state.us_portfolio_df,
    num_rows="dynamic", # 동적 행 추가/삭제 허용
    hide_index=True,
    use_container_width=True
)

st.sidebar.markdown("---")
st.sidebar.subheader("🇰🇷 한국 주식 (원화)")
edited_kr_df = st.sidebar.data_editor(
    st.session_state.kr_portfolio_df,
    num_rows="dynamic",
    hide_index=True,
    use_container_width=True
)

# 입력받은 DataFrame을 분석 로직에서 사용할 딕셔너리로 변환
portfolio_us = {}
for _, row in edited_us_df.iterrows():
    ticker = str(row["티커(Ticker)"]).strip().upper()
    if ticker and ticker != "NAN":
        portfolio_us[ticker] = {'shares': float(row.get("수량", 0) or 0), 'buy_price': float(row.get("매수단가($)", 0) or 0)}

portfolio_kr = {}
for _, row in edited_kr_df.iterrows():
    ticker = str(row["티커(6자리)"]).strip()
    if ticker and ticker != "NAN":
        # 한국 주식은 6자리 문자열로 맞춤 (예: 5930 -> 005930)
        ticker = ticker.zfill(6) if ticker.isdigit() else ticker
        portfolio_kr[ticker] = {'shares': float(row.get("수량", 0) or 0), 'buy_price': float(row.get("매수단가(₩)", 0) or 0)}

us_tickers = list(portfolio_us.keys())
kr_tickers = list(portfolio_kr.keys())
all_tickers = us_tickers + kr_tickers

# -------------------------------------------------------------------------
# 4. 공통 함수 정의 (RSI 계산 등)
# -------------------------------------------------------------------------
def calculate_rsi(series, window=14):
    """RSI(상대강도지수) 계산 함수"""
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=window).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=window).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

# -------------------------------------------------------------------------
# 5. 탭(Tab) 화면 분리
# -------------------------------------------------------------------------
tab1, tab2, tab3 = st.tabs(["📊 내 포트폴리오 분석", "🇰🇷 AI 한국 주식 스캐너", "🇺🇸 AI 미국 주식 스캐너"])

# =========================================================================
# TAB 1: 내 포트폴리오 분석 (하이브리드 데이터 로드)
# =========================================================================
with tab1:
    @st.cache_data(ttl=3600)
    def load_us_and_fx_data(tickers):
        tickers_to_fetch = tickers + ["USDKRW=X", "^GSPC", "^KS11"]
        try:
            data = yf.download(tickers_to_fetch, period="1y")['Close']
            return data
        except Exception:
            return pd.DataFrame()

    @st.cache_data(ttl=3600)
    def load_kr_data_fdr(tickers):
        start_date = datetime.today() - timedelta(days=365)
        df_list = []
        for t in tickers:
            try:
                df = fdr.DataReader(t, start_date)['Close']
                df.name = t
                df_list.append(df)
            except:
                pass
        if df_list:
            return pd.concat(df_list, axis=1)
        return pd.DataFrame()

    @st.cache_data(ttl=3600)
    def load_dividend_info(us_t, kr_t):
        div_yields = {}
        for t in us_t:
            try: div_yields[t] = yf.Ticker(t).info.get('dividendYield', 0) or 0
            except: div_yields[t] = 0
        for t in kr_t:
            try: div_yields[t] = yf.Ticker(f"{t}.KS").info.get('dividendYield', 0) or 0
            except: div_yields[t] = 0
        return div_yields

    if not all_tickers:
        st.warning("⚠️ 포트폴리오에 자산이 없습니다. 좌측 메뉴에서 종목을 추가해 주세요.")
    else:
        with st.spinner("미국 및 한국 금융 데이터를 동기화 중입니다..."):
            us_data = load_us_and_fx_data(us_tickers)
            kr_data = load_kr_data_fdr(kr_tickers)

            if not us_data.empty and not kr_data.empty:
                data = pd.concat([us_data, kr_data], axis=1).ffill().bfill()
            elif not us_data.empty:
                data = us_data.ffill().bfill()
            elif not kr_data.empty:
                # 미국 주식이 하나도 없을 경우 환율 처리를 위해 환율 데이터만 따로 받음
                fx_data = yf.download("USDKRW=X", period="1y")['Close']
                data = pd.concat([kr_data, fx_data], axis=1).ffill().bfill()
            else:
                st.error("🚨 데이터 로드 실패. 티커를 확인해 주세요.")
                st.stop()

            div_yields = load_dividend_info(us_tickers, kr_tickers)
            usd_krw_series = data["USDKRW=X"] if "USDKRW=X" in data else 1350.0
            current_fx = usd_krw_series.iloc[-1] if isinstance(usd_krw_series, pd.Series) else usd_krw_series

            stock_data_krw = pd.DataFrame(index=data.index)
            for ticker in us_tickers:
                if ticker in data:
                    stock_data_krw[ticker] = data[ticker] * usd_krw_series
            for ticker in kr_tickers:
                if ticker in data:
                    stock_data_krw[ticker] = data[ticker]

        total_invested_krw = 0
        us_profit_krw = 0

        # 유효한(데이터가 있는) 티커만 계산
        valid_tickers = [t for t in all_tickers if t in stock_data_krw.columns]

        for t in us_tickers:
            if t in valid_tickers:
                info = portfolio_us[t]
                invested = (info['buy_price'] * info['shares']) * current_fx
                total_invested_krw += invested
                us_profit_krw += (stock_data_krw[t].iloc[-1] * info['shares']) - invested

        for t in kr_tickers:
            if t in valid_tickers:
                info = portfolio_kr[t]
                total_invested_krw += (info['buy_price'] * info['shares'])

        if valid_tickers:
            current_prices_krw = stock_data_krw.iloc[-1]
            total_current_value_krw = sum(current_prices_krw[t] * (portfolio_us.get(t) or portfolio_kr.get(t))['shares'] for t in valid_tickers)

            if total_current_value_krw > 0:
                gross_profit = total_current_value_krw - total_invested_krw
                price_return_pct = (gross_profit / total_invested_krw * 100) if total_invested_krw > 0 else 0.0
                total_annual_dividend_krw = sum(current_prices_krw[t] * (portfolio_us.get(t) or portfolio_kr.get(t))['shares'] * div_yields.get(t, 0) for t in valid_tickers)

                dividend_tax = total_annual_dividend_krw * 0.154
                net_dividend = total_annual_dividend_krw - dividend_tax
                us_cap_gain_tax = max(0, us_profit_krw - 2500000) * 0.22
                net_profit = gross_profit - us_cap_gain_tax
                net_total_return_pct = ((net_profit + net_dividend) / total_invested_krw) * 100 if total_invested_krw > 0 else 0

                weights_dict = {t: (current_prices_krw[t] * (portfolio_us.get(t) or portfolio_kr.get(t))['shares']) / total_current_value_krw for t in valid_tickers}

                col1, col2 = st.columns([1, 1])
                with col1:
                    st.metric("총 평가 금액 (KRW)", f"₩{int(total_current_value_krw):,}")
                    st.metric("총 투자 원금 (KRW)", f"₩{int(total_invested_krw):,}")
                    st.metric("세후 최종 수익률 (전량 매도 가정)", f"{net_total_return_pct:.2f}%")
                with col2:
                    fig_pie, ax_pie = plt.subplots(figsize=(5, 5))
                    filtered_labels = [l for l, s in zip(weights_dict.keys(), weights_dict.values()) if s > 0]
                    filtered_sizes = [s for s in weights_dict.values() if s > 0]
                    if filtered_sizes:
                        ax_pie.pie(filtered_sizes, labels=filtered_labels, autopct='%1.1f%%', startangle=140, colors=plt.cm.Paired.colors)
                        ax_pie.axis('equal')
                        st.pyplot(fig_pie)
            else:
                st.warning("⚠️ 포트폴리오 가치가 0입니다.")
        else:
            st.error("🚨 유효한 티커를 찾을 수 없습니다. 티커명을 정확히 입력해 주세요.")


# =========================================================================
# TAB 2: 🇰🇷 AI 한국 주식 스캐너 (동일 유지)
# =========================================================================
with tab2:
    st.markdown("### 🔍 KOSPI / KOSDAQ 대형주 투자 매력도 스캐너")
    k_universe = {
        '005930': '삼성전자', '000660': 'SK하이닉스', '373220': 'LG에너지솔루션',
        '207940': '삼성바이오로직스', '005380': '현대차', '000270': '기아',
        '068270': '셀트리온', '005490': 'POSCO홀딩스', '035420': 'NAVER',
        '035720': '카카오', '086520': '에코프로', '247540': '에코프로비엠',
        '104480': '티웨이항공', '028300': 'HLB', '036570': '엔씨소프트'
    }

    if st.button("🚀 한국 마켓 스캔 시작"):
        with st.spinner("네이버 금융에서 탑티어 15개 종목을 스캔하고 있습니다..."):
            try:
                tickers_to_scan = list(k_universe.keys())
                start_date = datetime.today() - timedelta(days=180)

                df_list = []
                for ticker in tickers_to_scan:
                    df = fdr.DataReader(ticker, start_date)['Close']
                    df.name = ticker
                    df_list.append(df)

                scan_data = pd.concat(df_list, axis=1).ffill()
                results = []

                for ticker in tickers_to_scan:
                    prices = scan_data[ticker].dropna()
                    if len(prices) < 60: continue

                    current_price = prices.iloc[-1]
                    ma20 = prices.rolling(window=20).mean().iloc[-1]
                    ma60 = prices.rolling(window=60).mean().iloc[-1]
                    rsi_14 = calculate_rsi(prices).iloc[-1]

                    ret_1m = (current_price / prices.iloc[-21] - 1) * 100 if len(prices) >= 21 else 0
                    ret_3m = (current_price / prices.iloc[-63] - 1) * 100 if len(prices) >= 63 else 0

                    daily_ret = prices.pct_change().dropna()
                    volatility = daily_ret.std() * np.sqrt(252)
                    ann_ret = daily_ret.mean() * 252
                    sharpe = (ann_ret - 0.035) / volatility if volatility > 0 else 0

                    score = 0
                    if current_price > ma20: score += 20
                    if current_price > ma60: score += 20
                    if ret_3m > 5: score += 20
                    elif ret_3m > 0: score += 10
                    if 40 <= rsi_14 <= 70: score += 20
                    elif rsi_14 < 35: score += 10
                    if sharpe > 1.0: score += 20
                    elif sharpe > 0.5: score += 10

                    if score >= 80: status = "🔥 강력 매수 (주도주)"
                    elif score >= 60: status = "📈 상승 추세"
                    elif score >= 40: status = "⚖️ 횡보/관망"
                    else: status = "❄️ 하락 주의"

                    results.append({
                        "종목명": k_universe[ticker],
                        "AI 매력도 점수": score,
                        "상태": status,
                        "현재가(원)": f"{int(current_price):,}",
                        "1개월 수익률(%)": round(ret_1m, 2),
                        "RSI (상대강도)": round(rsi_14, 1),
                        "샤프 지수": round(sharpe, 2)
                    })

                df_results = pd.DataFrame(results).sort_values(by="AI 매력도 점수", ascending=False).reset_index(drop=True)
                df_results.index += 1
                st.dataframe(df_results.style.background_gradient(subset=['AI 매력도 점수', '1개월 수익률(%)'], cmap='Blues'), use_container_width=True)

            except Exception as e:
                st.error(f"스캔 중 오류가 발생했습니다: {e}")

# =========================================================================
# TAB 3: 🇺🇸 AI 미국 주식 스캐너 (동일 유지)
# =========================================================================
with tab3:
    st.markdown("### 🔍 S&P 500 / NASDAQ 대형주 투자 매력도 스캐너")
    us_universe = {
        'AAPL': 'Apple', 'MSFT': 'Microsoft', 'NVDA': 'NVIDIA',
        'GOOGL': 'Alphabet', 'AMZN': 'Amazon', 'META': 'Meta Platforms',
        'TSLA': 'Tesla', 'BRK-B': 'Berkshire Hathaway', 'LLY': 'Eli Lilly',
        'AVGO': 'Broadcom', 'JPM': 'JPMorgan Chase', 'UNH': 'UnitedHealth',
        'V': 'Visa', 'XOM': 'Exxon Mobil', 'JNJ': 'Johnson & Johnson'
    }

    if st.button("🚀 미국 마켓 스캔 시작"):
        with st.spinner("야후 파이낸스에서 미국 탑티어 15개 종목을 스캔하고 있습니다..."):
            try:
                tickers_to_scan = list(us_universe.keys())
                scan_data = yf.download(tickers_to_scan, period="6m")['Close']
                scan_data = scan_data.ffill()

                results = []
                for ticker in tickers_to_scan:
                    prices = scan_data[ticker].dropna()
                    if len(prices) < 60: continue

                    current_price = prices.iloc[-1]
                    ma20 = prices.rolling(window=20).mean().iloc[-1]
                    ma60 = prices.rolling(window=60).mean().iloc[-1]
                    rsi_14 = calculate_rsi(prices).iloc[-1]

                    ret_1m = (current_price / prices.iloc[-21] - 1) * 100 if len(prices) >= 21 else 0
                    ret_3m = (current_price / prices.iloc[-63] - 1) * 100 if len(prices) >= 63 else 0

                    daily_ret = prices.pct_change().dropna()
                    volatility = daily_ret.std() * np.sqrt(252)
                    ann_ret = daily_ret.mean() * 252
                    sharpe = (ann_ret - 0.035) / volatility if volatility > 0 else 0

                    score = 0
                    if current_price > ma20: score += 20
                    if current_price > ma60: score += 20
                    if ret_3m > 5: score += 20
                    elif ret_3m > 0: score += 10
                    if 40 <= rsi_14 <= 70: score += 20
                    elif rsi_14 < 35: score += 10
                    if sharpe > 1.0: score += 20
                    elif sharpe > 0.5: score += 10

                    if score >= 80: status = "🔥 강력 매수 (주도주)"
                    elif score >= 60: status = "📈 상승 추세"
                    elif score >= 40: status = "⚖️ 횡보/관망"
                    else: status = "❄️ 하락 주의"

                    results.append({
                        "종목명": us_universe[ticker],
                        "티커": ticker,
                        "AI 매력도 점수": score,
                        "상태": status,
                        "현재가($)": round(current_price, 2),
                        "1개월 수익률(%)": round(ret_1m, 2),
                        "RSI (상대강도)": round(rsi_14, 1),
                        "샤프 지수": round(sharpe, 2)
                    })

                df_results = pd.DataFrame(results).sort_values(by="AI 매력도 점수", ascending=False).reset_index(drop=True)
                df_results.index += 1
                st.dataframe(df_results.style.background_gradient(subset=['AI 매력도 점수', '1개월 수익률(%)'], cmap='Blues'), use_container_width=True)

            except Exception as e:
                st.error(f"스캔 중 오류가 발생했습니다: {e}")

